### ISSUE TITLE
WIC의 load_data.py special token 부분 질문드립니다.

### ISSUE THREAD

**Issue by kookeej** [NIKL-Team-BC/NIKL-KLUE#4]
안녕하세요, Team BC의 코드를 공부하다가 궁금한 점이 생겨 이렇게 질문 드립니다.

WIC의 load_data.py의 convert_sentence_to_features 부분을 보면,
라인 66~69에서
```python
e11_p += 1
e12_p += 1
e21_p += 1
e22_p += 1
```
이런 코드를 볼 수 있습니다. 이는 sentence의 맨 앞에 [cls] 토큰이 추가되기 때문에 해주는 처리라고 이해했습니다.

하지만 라인 46~54를 보면,
```python
sentence = '<s>' + train_dataset['SENTENCE1'][idx][:train_dataset['start_s1'][idx]] \
            + ' <e1> ' + train_dataset['SENTENCE1'][idx][train_dataset['start_s1'][idx]:train_dataset['end_s1'][idx]] \
            + ' </e1> ' + train_dataset['SENTENCE1'][idx][train_dataset['end_s1'][idx]:] + '</s>' \
            + ' ' \
            + '<s>' + train_dataset['SENTENCE2'][idx][:train_dataset['start_s2'][idx]] \
            + ' <e2> ' + train_dataset['SENTENCE2'][idx][train_dataset['start_s2'][idx]:train_dataset['end_s2'][idx]] \
            + ' </e2> ' + train_dataset['SENTENCE2'][idx][train_dataset['end_s2'][idx]:] + '</s>'

token = tokenizer.tokenize(sentence)
```
미리 `<s>` 토큰을 붙여준 뒤에 토큰화를 해줍니다. 이때 tokenizer에 special token으로는 `<e1>`,`</e1>`,`<e2>`,`</e2>`만 추가되었기 때문에 `<s>`,`</s>`토큰은 `['<', 's', '>']`와 같이 쪼개져서 나옵니다.
그래서 미리 `<s>`토큰을 붙여준 뒤 토큰화를 하면 `<s>`토큰은 분리되어 나오게 되고, 확인해본 결과 `[cls]` 토큰은 따로 추가되지 않기 때문에 라인 66~69에서 `e1`, `e2` 토큰에 각각 1씩 더해주면 포착하고자 하는 Entity의 범위에서 벗어나게 되는 것 같은데, 이렇게 진행되는 것이 맞는지, 아니면 제가 코드를 잘못 이해한 것인지 궁금해서 질문드립니다.
만약 [cls] 토큰이 추가되는 것이 맞다면, `<s>`, `</s>`을 special token으로 추가하지 않았기 때문에 쪼개지게 되는데 굳이 추가한 이유가 있는지 궁금합니다.
답변해주신다면 너무 감사하겠습니다.

추가로 Team BC의 해당 코드를 리뷰하여 출처를 밝히고 깃헙과 블로그에 정리하고 싶은데 혹시 가능할지 여쭙니다! 
감사합니다.

**Comment by karim-moon** [comment]
안녕하세요 kookeej님,

1. 해당 부분은 생각하신바와 같이 동작합니다.
코드 수정 후 업데이트하도록 하겠습니다.

2. 출처를 밝혀주신다면 블로그에 정리본을 올려주셔도 됩니다. :)

감사합니다

**Comment by kookeej** [comment]
넵 답변 감사합니다!
